<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300">
</center>

# Lab for Final Project - Data Analytics for Canadian Crop Production Data Set

Estimated time needed: 45 minutes

# Assignment Scenario

Congratulations! You have just been hired by a US Venture Capital firm as a data analyst.

The company is considering foreign grain markets to help meet its supply chain requirements for its recent investments in the microbrewery and microdistillery industry, which is involved with the production and distribution of craft beers and spirits.

Your first task is to provide a high level analysis of crop production in Canada. Your stakeholders want to understand the current and historical performance of certain crop types in terms of supply and price volatility. For now they are mainly interested in a macro-view of Canada's crop farming industry, and how it relates to the relative value of the Canadian and US dollars.

# Introduction

Using this R notebook you will:

1.  Understand four datasets
2.  Load the datasets into four separate tables in a database
3.  Execute SQL queries to answer assignment questions

You have already encountered two of these datasets in the previous practice lab. You will be able to reuse much of the work you did there to prepare your database tables for executing SQL queries.

# Understand the datasets

To complete the assignment problems in this notebook you will be using subsetted snapshots of two datasets from Statistics Canada, and one from the Bank of Canada. The links to the prepared datasets are provided in the next section; the interested student can explore the landing pages for the source datasets as follows:

1.  <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMRP0203ENSkillsNetwork23863830-2021-01-01&pid=3210035901">Canadian Principal Crops (Data & Metadata)</a>
2.  <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMRP0203ENSkillsNetwork23863830-2021-01-01&pid=3210007701">Farm product prices (Data & Metadata)</a>
3.  <a href="https://www.bankofcanada.ca/rates/exchange/daily-exchange-rates?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMRP0203ENSkillsNetwork23863830-2021-01-01">Bank of Canada daily average exchange rates</a>

### 1. Canadian Principal Crops Data \*

This dataset contains agricultural production measures for the principle crops grown in Canada, including a breakdown by province and teritory, for each year from 1908 to 2020.

For this assignment you will use a preprocessed snapshot of this dataset (see below).

A detailed description of this dataset can be obtained from the StatsCan Data Portal at:
[https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3210035901](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMRP0203ENSkillsNetwork23863830-2021-01-01&pid=3210035901)\
Detailed information is included in the metadata file and as header text in the data file, which can be downloaded - look for the 'download options' link.

### 2. Farm product prices

This dataset contains monthly average farm product prices for Canadian crops and livestock by province and teritory, from 1980 to 2020 (or 'last year', whichever is greatest).

For this assignment you will use a preprocessed snapshot of this dataset (see below).

A description of this dataset can be obtained from the StatsCan Data Portal at:
[https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3210007701](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMRP0203ENSkillsNetwork23863830-2021-01-01&pid=3210007701)
The information is included in the metadata file, which can be downloaded - look for the 'download options' link.

### 3. Bank of Canada daily average exchange rates \*

This dataset contains the daily average exchange rates for multiple foreign currencies. Exchange rates are expressed as 1 unit of the foreign currency converted into Canadian dollars. It includes only the latest four years of data, and the rates are published once each business day by 16:30 ET.

For this assignment you will use a snapshot of this dataset with only the USD-CAD exchange rates included (see next section). We have also prepared a monthly averaged version which you will be using below.

A brief description of this dataset and the original dataset can be obtained from the Bank of Canada Data Portal at:
[https://www.bankofcanada.ca/rates/exchange/daily-exchange-rates/](https://www.bankofcanada.ca/rates/exchange/daily-exchange-rates/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMRP0203ENSkillsNetwork23863830-2021-01-01)

( \* these datasets are the same as the ones you used in the practice lab)

### Dataset URLs

1.  Annual Crop Data: <https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-RP0203EN-SkillsNetwork/labs/Final%20Project/Annual_Crop_Data.csv>

2.  Farm product prices: <https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-RP0203EN-SkillsNetwork/labs/Final%20Project/Monthly_Farm_Prices.csv>

3.  Daily FX Data: <https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-RP0203EN-SkillsNetwork/labs/Final%20Project/Daily_FX.csv>

4.  Monthly FX Data: <https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-RP0203EN-SkillsNetwork/labs/Final%20Project/Monthly_FX.csv>

<span style="color:red">**IMPORTANT:**</span> You will be loading these datasets directly into R data frames from these URLs instead of from the StatsCan and Bank of Canada portals. The versions provided at these URLs are simplified and subsetted versions of the original datasets.

#### Now let's load these datasets into four separate tables.

Let's first load the RSQLite package. 

Note: If you encounter a `non-zero exist status`, don't worry as it doesn't affect the functionality of the lab.

In [1]:
install.packages("https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_0.10.0.tar.gz", repos = NULL, type = "source", dependencies = TRUE)

Warning message in install.packages("https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_0.10.0.tar.gz", :
“installation of package ‘/tmp/RtmpxszeC7/downloaded_packages/RSQLite_0.10.0.tar.gz’ had non-zero exit status”

#### Restart Kernel

After installing the RSQLite package, it is necessary to restart R Kernel. Click **Kernel** > **Restart Kernel** from the main menu. This will register the newly installed packages. Now proceed to load the RSQLite package.

In [1]:
library("RSQLite")

## Problem 1

#### Create tables

Establish a connection **conn** to the RSQLite database **FinalDB.sqlite**, and create the following four tables.

1.  **CROP_DATA**
2.  **FARM_PRICES**
3.  **DAILY_FX**
4.  **MONTHLY_FX**

The previous practice lab will help you accomplish this.

In [4]:
# Write your query here
conn <- dbConnect(RSQLite::SQLite(), "FinalDB.sqlite")

df1 <- dbExecute(conn, 
                    "CREATE TABLE CROP_DATA (
                                      CD_ID INTEGER NOT NULL,
                                      YEAR DATE NOT NULL,
                                      CROP_TYPE VARCHAR(20) NOT NULL,
                                      GEO VARCHAR(20) NOT NULL, 
                                      SEEDED_AREA INTEGER NOT NULL,
                                      HARVESTED_AREA INTEGER NOT NULL,
                                      PRODUCTION INTEGER NOT NULL,
                                      AVG_YIELD INTEGER NOT NULL,
                                      PRIMARY KEY (CD_ID)
                                      )")

df2 <- dbExecute(conn, 
                    "CREATE TABLE DAILY_FX (
                                      DFX_ID INTEGER NOT NULL,
                                      DATE DATE NOT NULL,
                                      FXUSDCAD FLOAT(6),
                                      PRIMARY KEY (DFX_ID)
                                      )")

df3 <- dbExecute(conn, 
                    "CREATE TABLE FARM_PRICES (
                                      CD_ID INTEGER NOT NULL, 
                                      DATE DATE NOT NULL,
                                      CROP_TYPE VARCHAR(20) NOT NULL,
                                      GEO VARCHAR(20) NOT NULL, 
                                      PRICE_PRERMT DECIMAL (6, 2) NOT NULL,
                                      PRIMARY KEY (CD_ID)
                                      )")

df4 <- dbExecute(conn, 
                    "CREATE TABLE MONTHLY_FX (
                                      DFX_ID INTEGER NOT NULL,
                                      DATE DATE NOT NULL,
                                      FXUSDCAD FLOAT(6),
                                      PRIMARY KEY (DFX_ID)
                                      )")

In [5]:
#check list of tables in the present db.
dbListTables(conn)

[1] "CROP_DATA"   "DAILY_FX"    "FARM_PRICES" "MONTHLY_FX"

## Problem 2

#### Read Datasets and load your tables in database

Read the datasets into R dataframes using the urls provided above. Then load your tables in database.

In [9]:
# Write your query here

crop_df <- read.csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-RP0203EN-SkillsNetwork/labs/Final%20Project/Annual_Crop_Data.csv')
daily_df <- read.csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-RP0203EN-SkillsNetwork/labs/Final%20Project/Daily_FX.csv')
farm_df <- read.csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-RP0203EN-SkillsNetwork/labs/Final%20Project/Monthly_Farm_Prices.csv')
monthly_df <- read.csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-RP0203EN-SkillsNetwork/labs/Final%20Project/Monthly_FX.csv')


# Loading the datasets into the database
dbWriteTable(conn, 'CROP_DATA', crop_df, overwrite=TRUE, header = TRUE)
dbWriteTable(conn, 'DAILY_FX', daily_df, overwrite=TRUE, header = TRUE)
dbWriteTable(conn, 'FARM_PRICES', farm_df, overwrite=TRUE, header = TRUE)
dbWriteTable(conn, 'MONTHLY_FX', monthly_df, overwrite=TRUE, header = TRUE)

head(crop_df)
head(daily_df)
head(farm_df)
head(monthly_df)

  CD_ID YEAR       CROP_TYPE GEO          SEEDED_AREA HARVESTED_AREA PRODUCTION
1 0     1965-12-31 Barley    Alberta      1372000     1372000        2504000
2 1     1965-12-31 Barley    Canada       2476800     2476800        4752900
3 2     1965-12-31 Barley    Saskatchewan  708000      708000        1415000
4 3     1965-12-31 Canola    Alberta       297400      297400         215500
5 4     1965-12-31 Canola    Canada        580700      580700         512600
6 5     1965-12-31 Canola    Saskatchewan  224600      224600         242700
  AVG_YIELD
1 1825
2 1920
3 2000
4  725
5  885
6 1080

  DFX_ID DATE       FXUSDCAD
1 0      2017-01-03 1.3435
2 1      2017-01-04 1.3315
3 2      2017-01-05 1.3244
4 3      2017-01-06 1.3214
5 4      2017-01-09 1.3240
6 5      2017-01-10 1.3213

  CD_ID DATE       CROP_TYPE GEO          PRICE_PRERMT
1 0     1985-01-01 Barley    Alberta      127.39
2 1     1985-01-01 Barley    Saskatchewan 121.38
3 2     1985-01-01 Canola    Alberta      342.00
4 3     1985-01-01 Canola    Saskatchewan 339.82
5 4     1985-01-01 Rye       Alberta      100.77
6 5     1985-01-01 Rye       Saskatchewan 109.75

  DFX_ID DATE       FXUSDCAD
1 0      2017-01-01 1.319276
2 1      2017-02-01 1.310726
3 2      2017-03-01 1.338643
4 3      2017-04-01 1.344021
5 4      2017-05-01 1.360705
6 5      2017-06-01 1.329805

## Now execute SQL queries using the RSQLite R package to solve the assignment problems.

## Problem 3

#### How many records are in the farm prices dataset?

In [11]:
# Write your query here
dbGetQuery(conn, 'SELECT COUNT(*) FROM FARM_PRICES')

  COUNT(*)
1 2678

## Problem 4

#### Which geographies are included in the farm prices dataset?

In [14]:
# Write your query here
dbGetQuery(conn, "SELECT DISTINCT(GEO) FROM FARM_PRICES")

  GEO
1 Alberta
2 Saskatchewan

## Problem 5

#### How many hectares of Rye were harvested in Canada in 1968?

In [19]:
# Write your query here
dbGetQuery(conn, "SELECT SUM(HARVESTED_AREA) 
FROM CROP_DATA
WHERE CROP_TYPE = 'Rye' AND GEO = 'Canada' AND
SUBSTR(YEAR, 1,4) = '1968' ") #SUBSTR(year, 1, 4) helps to extract the first four characters from "YEAR" starting at position 1. This is important because the YEAR column stores full ISO date strings as 1968-mm-dd

  SUM(HARVESTED_AREA)
1 274100

## Problem 6

#### Query and display the first 6 rows of the farm prices table for Rye.

In [20]:
# Wriet your query here
dbGetQuery(conn, "SELECT * FROM FARM_PRICES WHERE CROP_TYPE = 'Rye' LIMIT 6")

  CD_ID DATE       CROP_TYPE GEO          PRICE_PRERMT
1  4    1985-01-01 Rye       Alberta      100.77
2  5    1985-01-01 Rye       Saskatchewan 109.75
3 10    1985-02-01 Rye       Alberta       95.05
4 11    1985-02-01 Rye       Saskatchewan 103.46
5 16    1985-03-01 Rye       Alberta       96.77
6 17    1985-03-01 Rye       Saskatchewan 106.38

## Problem 7

#### Which provinces grew Barley?

In [21]:
# Write your query here

dbGetQuery(conn, "SELECT DISTINCT(GEO) FROM FARM_PRICES WHERE CROP_TYPE = 'Barley' ")

  GEO
1 Alberta
2 Saskatchewan

## Problem 8

#### Find the first and last dates for the farm prices data.

In [24]:
# Write your query here
dbGetQuery(conn, "SELECT min(DATE) FIRST_DATE, max(DATE) LAST_DATE FROM FARM_PRICES")

  FIRST_DATE LAST_DATE
1 1985-01-01 2020-12-01

## Problem 9

#### Which crops have ever reached a farm price greater than or equal to $350 per metric tonne?

In [26]:
# Write your query here
dbGetQuery(conn, "SELECT DISTINCT(CROP_TYPE), PRICE_PRERMT FROM FARM_PRICES WHERE PRICE_PRERMT >= 350 LIMIT 20")

   CROP_TYPE PRICE_PRERMT
1  Canola    350.04
2  Canola    363.84
3  Canola    364.36
4  Canola    354.58
5  Canola    359.99
6  Canola    350.47
7  Canola    354.05
8  Canola    354.82
9  Canola    357.37
10 Canola    368.18
11 Canola    373.35
12 Canola    381.30
13 Canola    380.24
14 Canola    384.32
15 Canola    358.59
16 Canola    357.67
17 Canola    367.46
18 Canola    367.09
19 Canola    390.35
20 Canola    390.01

## Problem 10

#### Rank the crop types harvested in Saskatchewan in the year 2000 by their average yield. Which crop performed best?

In [28]:
# Write your query here
dbGetQuery(conn, "SELECT DISTINCT(CROP_TYPE), GEO, AVG_YIELD 
           FROM CROP_DATA 
           WHERE GEO = 'Saskatchewan' AND SUBSTR(YEAR, 1,4) = '2000'
           ORDER BY AVG_YIELD DESC")

  CROP_TYPE GEO          AVG_YIELD
1 Barley    Saskatchewan 2800
2 Wheat     Saskatchewan 2200
3 Rye       Saskatchewan 2100
4 Canola    Saskatchewan 1400

## Problem 11

#### Rank the crops and geographies by their average yield (KG per hectare) since the year 2000. Which crop and province had the highest average yield since the year 2000?

In [30]:
# Write your query here
dbGetQuery(conn, "SELECT CROP_TYPE, GEO, AVG_YIELD, YEAR 
FROM CROP_DATA
WHERE SUBSTR(YEAR, 1,4) >= 2000
           ORDER BY AVG_YIELD DESC")

    CROP_TYPE GEO          AVG_YIELD YEAR
1   Barley    Alberta      4100      2013-12-31
2   Barley    Alberta      4100      2016-12-31
3   Barley    Alberta      3980      2020-12-31
4   Wheat     Alberta      3900      2013-12-31
5   Barley    Canada       3900      2016-12-31
6   Wheat     Alberta      3900      2016-12-31
7   Barley    Alberta      3900      2017-12-31
8   Barley    Alberta      3890      2019-12-31
9   Barley    Canada       3820      2020-12-31
10  Barley    Canada       3810      2019-12-31
11  Barley    Canada       3800      2013-12-31
12  Barley    Saskatchewan 3800      2016-12-31
13  Wheat     Alberta      3750      2020-12-31
14  Barley    Saskatchewan 3730      2019-12-31
15  Barley    Alberta      3700      2015-12-31
16  Barley    Canada       3700      2017-12-31
17  Rye       Alberta      3691      2020-12-31
18  Barley    Saskatchewan 3690      2020-12-31
19  Barley    Alberta      3600      2005-12-31
20  Barley    Alberta      3600      2008-12-31
21  Barley    Alberta      3600      2010-12-31
22  Barley    Alberta      3600      2011-12-31
23  Barley    Saskatchewan 3600      2013-12-31
24  Wheat     Canada       3600      2013-12-31
25  Barley    Alberta      3600      2014-12-31
26  Wheat     Canada       3600      2016-12-31
27  Barley    Saskatchewan 3600      2017-12-31
28  Barley    Alberta      3595      2018-12-31
29  Wheat     Alberta      3518      2019-12-31
30  Wheat     Canada       3512      2020-12-31
⋮   ⋮         ⋮            ⋮         ⋮
643 Canola    Saskatchewan 1000      1988-12-31
644 Canola    Saskatchewan 1000      1989-12-31
645 Canola    Saskatchewan 1000      2002-12-31
646 Canola    Alberta       990      1966-12-31
647 Rye       Saskatchewan  990      1969-12-31
648 Canola    Alberta       985      1970-12-31
649 Canola    Canada        980      1972-12-31
650 Canola    Saskatchewan  975      1966-12-31
651 Rye       Saskatchewan  975      1980-12-31
652 Canola    Saskatchewan  960      1979-12-31
653 Canola    Saskatchewan  955      1967-12-31
654 Canola    Canada        950      1966-12-31
655 Canola    Canada        945      1973-12-31
656 Canola    Alberta       935      1968-12-31
657 Canola    Canada        930      1969-12-31
658 Canola    Saskatchewan  930      1973-12-31
659 Canola    Saskatchewan  925      1972-12-31
660 Canola    Alberta       925      1973-12-31
661 Canola    Alberta       910      1974-12-31
662 Canola    Canada        910      1974-12-31
663 Rye       Saskatchewan  900      1967-12-31
664 Canola    Alberta       900      1971-12-31
665 Wheat     Saskatchewan  900      1988-12-31
666 Canola    Saskatchewan  895      1974-12-31
667 Canola    Canada        885      1965-12-31
668 Canola    Canada        850      1967-12-31
669 Canola    Alberta       805      1969-12-31
670 Rye       Saskatchewan  800      1988-12-31
671 Canola    Alberta       780      1967-12-31
672 Canola    Alberta       725      1965-12-31

## Problem 12

#### Use a subquery to determine how much wheat was harvested in Canada in the most recent year of the data.

In [32]:
# Write your query here
dbGetQuery(conn, "SELECT CROP_TYPE, HARVESTED_AREA 
FROM CROP_DATA
WHERE CROP_TYPE = 'Wheat' 
           AND GEO = 'Canada' 
           AND SUBSTR(YEAR, 1,4) = (SELECT MAX(SUBSTR(YEAR, 1,4)) FROM CROP_DATA)")

  CROP_TYPE HARVESTED_AREA
1 Wheat     10017800

## Problem 13

#### Use an implicit inner join to calculate the monthly price per metric tonne of Canola grown in Saskatchewan in both Canadian and US dollars. Display the most recent 6 months of the data.

In [33]:
# Write your query here
dbGetQuery(conn, "SELECT F.DATE, F.CROP_TYPE, F.GEO, F.PRICE_PRERMT, (F.PRICE_PRERMT / M.FXUSDCAD), M.FXUSDCAD FROM FARM_PRICES F, MONTHLY_FX M
WHERE SUBSTR(F.DATE, 1,4)=SUBSTR(M.DATE, 1,4)
AND SUBSTR(F.DATE, 6,2) = SUBSTR(M.DATE, 6,2)
AND CROP_TYPE = 'Canola' AND GEO = 'Saskatchewan'
ORDER BY F.DATE DESC LIMIT 6 ")

  DATE       CROP_TYPE GEO          PRICE_PRERMT (F.PRICE_PRERMT / M.FXUSDCAD)
1 2020-12-01 Canola    Saskatchewan 507.33       396.1128
2 2020-11-01 Canola    Saskatchewan 495.64       379.2718
3 2020-10-01 Canola    Saskatchewan 474.80       359.2965
4 2020-09-01 Canola    Saskatchewan 463.52       350.4057
5 2020-08-01 Canola    Saskatchewan 464.60       351.3827
6 2020-07-01 Canola    Saskatchewan 462.88       342.9122
  FXUSDCAD
1 1.280771
2 1.306820
3 1.321471
4 1.322810
5 1.322205
6 1.349850

## Author(s)

<h4> Jeff Grossman </h4>

<h4> D.M. Naidu </h4>

## Contributor(s)

<h4> Rav Ahuja </h4>

<h4> Lakshmi Holla </h4>

![footer](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/zOMU1iwlZgwJXjWYzQAIgg/SNIBMfooter.png "footer")


<!--## Change log

| Date       | Version | Changed by    | Change Description                        |
| ---------- | ------- | ------------- | ----------------------------------------- |
| 2022-03-03 | 1.0     | D.M. Naidu    | Converted intial version to RSQLite       |-->